// admin/app/components/ui/separator/Separator.vue
<script setup lang="ts">
  import { reactiveOmit } from '@vueuse/core'
  import type { SeparatorProps } from 'reka-ui'
  import { Separator } from 'reka-ui'
  import type { HTMLAttributes } from 'vue'
  import { cn } from '@/lib/utils'

  const props = withDefaults(
    defineProps<SeparatorProps & { class?: HTMLAttributes['class'] }>(),
    {
      orientation: 'horizontal',
      decorative: true
    }
  )

  const delegatedProps = reactiveOmit(props, 'class')
</script>

<template>
  <Separator
    data-slot="separator"
    v-bind="delegatedProps"
    :class="
      cn(
        'bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        props.class
      )
    "
  />
</template>

// mobile/src/components/ui/separator.tsx
import * as SeparatorPrimitive from '@rn-primitives/separator'
import { cn } from '@/lib/utils'

function Separator({
  className,
  orientation = 'horizontal',
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      decorative={decorative}
      orientation={orientation}
      className={cn(
        'bg-border shrink-0',
        orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
        className
      )}
      {...props}
    />
  )
}

export { Separator }
